### ISSUE TITLE
Display json on html and more question

### ISSUE THREAD

**Issue by vietlib** [botika/yarte#102]
I use actix-web and môngdb. How can i display json respond from api please

**Comment by botika** [comment]
If you use `serde`, with the following Rust code:
```rust
use serde::Serialize;

#[derive(Template)]
#[template(path = "foo-file")]
struct Json<S: Serialize> {
    foo: S
}
```
And template:
```handlebars
{{{ serde_json::to_string(&foo).map_err(|_| yarte::Error)? }}}
```

**Comment by vietlib** [comment]
how can i call template for each a request please ?

**Comment by botika** [comment]
In the example directory you have an example

**Comment by botika** [comment]
If you want to use the git version, you can use:
In `Cargo.toml`:
```toml
yarte = { git = "https://github.com/botika/yarte", features = ["json"] }
```

In template:
```handlebars
{{ @json obj }}
```
It has better performance than the previous solution:

```handlebars
{{{ serde_json::to_string(&obj).map_err(|_| yarte::Error)? }}}
```

Any other question? Or close it?

**Comment by vietlib** [comment]
can you make a full example please ? such as: get data from mongodb and display with yarte ?

**Comment by botika** [comment]
Can use https://github.com/mongodb/mongo-rust-drive.
https://github.com/mongodb/mongo-rust-driver#finding-documents-in-a-collection
And put result in array. I don't know, never use mongodb in Rust.

If you want a good performance use Postgres-sql, I leave you the [example](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Rust/actix/src/main_pg.rs#L88-L111) and [actix-pg benchmarks](https://www.techempower.com/benchmarks/#section=test&runid=6f06e4f2-019f-4a24-8650-89d5ba53dd80)

**Comment by vietlib** [comment]
I have a function return data from Postgresql like below: 
`#[derive(Clone, Debug, Serialize, Deserialize, Queryable)]
pub struct Users {
    pub email: String,
    pub password: String,
    pub created_at: String,

}

#[derive(Serialize, Deserialize, Queryable, Clone)] 
pub struct UserList(pub Vec<Users>);

impl UserList {
    pub fn list() -> Self {
        // These four statements can be placed in the top, or here, your call.
        use diesel::RunQueryDsl;
        use diesel::QueryDsl;
        use crate::schema::users::dsl::*;
        use crate::db::db_connection::establish_connection;

        let connection = establish_connection();

        let result = 
            users
                .limit(10)
                .load::<Users>(&connection)
                .expect("Error loading products");
                
        // We return a value by leaving it without a comma
        UserList(result)
    }
}`

How can i write an handler that list all user (json data respond) please

**Comment by botika** [comment]
Not use diesel, not allow multiplexing. Here https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Rust/actix/src/db_pg.rs#L30 the implementation of Postgres Actor. And the handler https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Rust/actix/src/db_pg.rs#L183-L218 .

**Comment by vietlib** [comment]
I know how  to write a handler but i want to ask you is how to display json data return from UserList(result) above. Thank you

**Comment by botika** [comment]
If use your `User` struct:
```toml
yarte = { version = "0.8", features=["json"] }
```
```rust
#[derive(Template)]
#[template(src ="{{# each users }}{{ @json this }}{{/each }}")]
struct Template { users: Vec<Users> }

async fn get_template(....) -> future::Ready<HttpResponse, Error> {
  /* Get from database, cache, etc.... */
  match Template { users: /* your users */ }.call() {
    Ok(body) => future::ok(HttpResponse::Ok().content_type("....").body(body),
    Err(err) => future::err(...),
}
```

**Comment by vietlib** [comment]
My handler.rs is: 
```
use actix_web::{HttpRequest, HttpResponse};
use crate::models::users::UserList;
use yarte::Template;


#[derive(Template)]
#[template(src ="{{# each users }}{{ @json this }}{{/each }}")]
struct Template { users: Vec<Users> }

async fn get_template(....) -> future::Ready<HttpResponse, Error> {
    let list = UserList::list();
  /* Get from database, cache, etc.... */
  match Template { users: list }.call() {
    Ok(body) => future::ok(HttpResponse::Ok().content_type("....").body(body),
    Err(err) => future::err(...),
}
```


And my main.rs is: 
```
#[actix_rt::main]
async fn main() -> io::Result<()> {
    // Handlebars uses a repository for the compiled templates. This object must be
    // shared between the application threads, and is therefore passed to the
    // Application Builder as an atomic reference-counted pointer.
    HttpServer::new(move || {
        App::new()
            .service(handlers::user_handler::index)
    })
    .bind("127.0.0.1:8080")?
    .run()
    .await
}
```

And my template is:

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Vietlib</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!--
</head>

<body>
{{ @json users.name }}
{{ @json users.email }}
</body>
</html>
```

But it not work for me

**Comment by botika** [comment]
Edited, but I recommend that you read this [book](https://en.wikipedia.org/wiki/The_C_Programming_Language) before you start programming with Rust.

**Comment by vietlib** [comment]
Thank you so much

**Comment by vietlib** [comment]
Can you make an example on display some json data on a page please ? For example , i want to display some users and some ebooks, some articles on homepage (please use some sample json data). Use, ebook, article are json data get respond from server. Thank you so much

**Comment by botika** [comment]
https://medium.com/swlh/creating-a-web-and-api-authentication-service-in-rust-55d0b0a848d

**Comment by vietlib** [comment]
Im sorry to disturb you, but i still can not make yarte run with my script, I have updated my script to google driver, can you help me display user data with yarte : template link with follow: `/templates/user/list.hbs.`

My script query to postgres data and respond all data to json at: ` scr/user/routes.rs`
Besides, i have custome error at: src/error.rs, which handle all API's error 

My script link: https://drive.google.com/open?id=1cTrCZQE8yv8Y2fAvtXOYon-X5HdgDNmh

Thank you so much !

Your template benmark is great , so i still want to use yarte instead of other template engine.

**Comment by botika** [comment]
Sorry but I am unemployed, and I also have the misfortune of being born in Spain, my knowledge of English is minimal and I am trapped in Fachiland vacation city. 

Throughout the next week I will make a repo with a complete application example with Postgres.

**Comment by vietlib** [comment]
I have a problem and hope you can give me a suggestion: 
I have homepage with : header, body and footer. The header contain login link if user not logged in , and display logout link if user logged in. In body , it display all products which query from database. Can I ask you how to make it display logged in link if user not login and when logged IN, it will display logged out link. I have looked into : https://yarte.netlify.app/templating/rust_code.html
but I am not sure how to do it ? 

Thank you so much !

**Comment by botika** [comment]
Damn man, well with a Boolean, I don't know what has to do with the template. 

I don't mean to insult you, but reality isn't always pretty

This is not nodejs or python that looking at stackoverflow and osmosis works, if you do not understand that you need a boolean it is that your mind is not prepared for this level of logic. 

Use [askama](https://github.com/djc/askama) which is more for this type of person, osmosis person, and ask the one who works for ING Direct.
