### ISSUE TITLE
using the .html extension

### ISSUE THREAD

**Issue by pahgre** [botika/yarte#112]
When trying to use the .html extension like the example (https://yarte.netlify.app/getting_started.html), I am getting the following error: **Default extension for yarte templates is `.hbs`**

Is there any way to use the .html extension?  I am running some other pre-processing that produces this extension.

**Comment by botika** [comment]
Sorry the documentation is outdated. 

In version 0.8 I set `hbs` extension as default. You can fix it with a script with `mv foo.html foo.hbs`

**Comment by pahgre** [comment]
I am using Parcel to tree shake my javascript and css.  I will run a script to rename all of the files from html to hbs.

Thanks for the quick response.
