### ISSUE TITLE
`char` type is not escaped

### ISSUE THREAD

**Issue by Kogia-sima** [botika/yarte#125]
## description

When `char` type is passed to template, it is not escaped.

## Example

Template:

```
<h1>{{ content }}</h1>
```

Rust code:

```rust
use yarte::Template;

#[derive(Template)]
#[template(path = "example.hbs")]
struct Example {
    content: char
}

fn main() {
    let template = Example { content: '<' };
    println!("{}", template.call().unwrap());
}
```

Output:

```
<h1><</h1>
```

**Comment by botika** [comment]
Yes, it does not escape. It is quite ineffective to pass v_escape. There should have been notice from the documentation, sorry. I'm going to put new features to v_escape including this one. 

Thank you very much for warning.
