### ISSUE TITLE
Allow code to build when .html template has been changed.

### ISSUE THREAD

**Issue by cy6erlion** [botika/yarte#13]
Hi, thank you for the awesome crate!

I am having a little problem, when I change a template (.html) and rebuild the project those changes don't take effect, they only change when I build the .rs file where the template struct has been declared.

**Comment by botika** [comment]
Need to add a file `build.rs` with:

```
use yarte::recompile;

fn main() {
    recompile::when_changed();
}
```

**Comment by shiftrtech** [comment]
I have a bin project (using actix-web) and this error: `use of undeclared crate or module 'yarte'`
