### ISSUE TITLE
Code print can alloc too big

### ISSUE THREAD

**Issue by botika** [botika/yarte#147]
When compile `example` with code logger activated, returns:
```
not memory allocation of 8391155392347897856 bytes failed
```

Some components of logger have a bug. Not use in `0.11.0` and previous and `rustc 1.46.0-nightly (6bb3dbfc6 2020-06-22) previous`. In nightly works well.

**Comment by DevinR528** [comment]
I seem to have this exact same issue (the exact same amount I got here by googling the specific number). Completely unrelated project though, hmmm?? https://github.com/DevinR528/rumatui/tree/ruma22

**Comment by botika** [comment]
I haven't looked at anything, but it has to be directly related to the dependent crates for the code logger, I think `prettryprint`. I don't know, tomorrow I'll check it.

**Comment by botika** [comment]
Confirmed the bug is in `prettyprint@0.8.1` crate

**Comment by DevinR528** [comment]
It's almost got to be how [`syntect`]() a dep of prettyprint and one of the crates I used. I found it was either https://docs.rs/syntect/4.2.0/src/syntect/dumps.rs.html#81 or https://docs.rs/syntect/4.2.0/src/syntect/dumps.rs.html#131 the files it serializes into binary are big.

I was doing this in a tight async event loop with lots of calls to a function that reallocated both of these everytime. Hope this helps.
