### ISSUE TITLE
Runtime-provided templates

### ISSUE THREAD

**Issue by SirWindfield** [botika/yarte#172]
I currently have a use-case where users should be able to provide the template and I just fill it in during runtime and generate the resulting text. Is this possible with yarte? All examples show that you have to specify the path to the template, but in my case this is not possible.

**Comment by botika** [comment]
The template will never be incorporated at runtime. For security and performance reasons the logic of must be known at compile time. I recommend you frame all your logic in compilation time.

**Comment by SirWindfield** [comment]
I normally do agree on that, but in my use case that doesn't really matter.
I did hope that it was possible with yarte as it is one of the faster frameworks.

**Comment by botika** [comment]
With kubernetes you can compile and serve the container in a safe and fast way without the need for the framework to have support for it.

**Comment by SirWindfield** [comment]
Thanks for pointing me out to an alternative :)

**Comment by botika** [comment]
You can implement a template in runtime implement `Render*` or `fmt :: Display` traits. Even integrate the nested `tera` template or any other. An example is https://docs.rs/yarte/0.12.1/yarte/struct.Json.html. https://docs.rs/yarte/0.12.1/yarte/#traits 

Excuse me, I thought that with your mastery you would have taken it into account.

**Comment by SirWindfield** [comment]
Oh, I skimmed through the docs but it seems that I missed the render traits. Thanks for pointing them out!
