### ISSUE TITLE
Why do abstractions have a cost?

### ISSUE THREAD

**Issue by botika** [botika/yarte#179]
I don't know of any 'no cost' framework. 
IT energy consumption is skyrocketing and it is the beginning, but the industry adds superfluous costs.

Is it really necessary? My answer is no. By typing and metaprogramming it is possible to build a framework at no cost in runtime.

It's really already being done in low-level implementations.

The web and mobile are working under abstractions with a cost that in most cases is enormous. If we multiply by the number of executions the useless expense created by the profit of a few who control the distribution markets is totally idiotic. In these cases javascript and java seem to be the kings, in the realm of planetary entropy.

With a quick search we see that in Javascript the consumption of finite resources (second principle of thermodynamics) to do absolutely the same. But consumption soars in the case of WASM.

https://timkadlec.com/remembers/2020-04-21-the-cost-of-javascript-frameworks/

Actually, the only idea to try in yarte is how to create abstractions without entailing a much higher cost than the raw implementation.

It's a draft, I will continue it

**Comment by gxtaillon** [comment]
I +1'd yarte and this very much :)

Javascript hurts power efficiency and it hurts latency (more stuff to DL, more stuff to parse, more stuff to execute, etc.).

The only way I managed to get the UI of my current project a 100/100 on lighthouse and below 10ms latency is to turn off Javascript completely. I think this is very much the future as it's not only much more simple to run but the devstack is microscopic as well compared to typescript/babel/yarn/npm &co.
