### ISSUE TITLE
My English is terrible and the documentation I wrote must have many typo errors 

### ISSUE THREAD

**Issue by botika** [botika/yarte#215]
When I wrote the documentation I did most of it with the translator so it must have a lot of errors. The book should be revised and rewritten correctly.

**Comment by himanshu007-creator** [comment]
Please assign me this issue .

**Comment by botika** [comment]
For you the issue, thank you very much. Please remember to launch `mdbook build` before uploading it, so that it will update on netifly.

**Comment by botika** [comment]
You need mdbook, for install it:
```bash
cargo install mdbook
```
After commit execute:
```bash
cd book
mdbook build
```

Netifly has a hook that will serve the `book/book` directory.

**Comment by himanshu007-creator** [comment]
can you specify which files in documentation you want a review? or all of 'em?!

**Comment by shiftrtech** [comment]
De dónde eres @botika?

**Comment by botika** [comment]
> can you specify which files in documentation you want a review? or all of 'em?!

all of them

**Comment by botika** [comment]
> De dónde eres @botika?

@shiftrtech Por desgracia me encuentro atrapado en Barcelona. En este estado fascista que llaman España. Tienes un email en mis repositorios por si te quieres ponerte en contacto conmigo.

**Comment by botika** [comment]
@himanshu007-creator Do you still want to take this issue? The only documentation that should be looked at carefully is that of the book. The code is refactoring to allow the use of more languages so it will change greatly.

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator Do you still want to take this issue? The only documentation that should be looked at carefully is that of the book. The code is refactoring to allow the use of more languages so it will change greatly.

I would work on it, please mention the file location, I would work on it

**Comment by botika** [comment]
Is in `book` directory, the `*.md` files.
