### ISSUE TITLE
win10  don't run simple project throw error

### ISSUE THREAD

**Issue by 853103174** [botika/yarte#216]
use MinGW-w64-posix-seh run simple project throw error
 D:/Rust/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: Error: export ordinal too large: 76628
          collect2.exe: error: ld returned 1 exit status
error: aborting due to previous error
error: could not compile `yarte_derive`

**Comment by botika** [comment]
There are too many symbols for compiling the DLLs. https://lists.llvm.org/pipermail/llvm-dev/2019-June/133204.html
I recommend using Linux for everything (especially to make a DirectX compatible fork)
