### ISSUE TITLE
does not compile with rust 1.52.1

### ISSUE THREAD

**Issue by fafhrd91** [botika/yarte#223]

**Comment by fafhrd91** [comment]
https://tfb-status.techempower.com/unzip/results.2021-06-06-03-33-04-151.zip/results/20210601100659/ntex/build/ntex.log

**Comment by botika** [comment]
Sorry, my bad. Now I release a new version.

**Comment by botika** [comment]
The new version is now available. In techempower you don't have to do anything since the version is `0.15`. Sorry.
