### ISSUE TITLE
Add Render support for uuid::Uuid (alloc::string::ToString)

### ISSUE THREAD

**Issue by Chaostheorie** [botika/yarte#225]
Hey! Thank you for maintaining and building this awesome templating library. I've recently started migrating to it from askama and really enjoyed the thorough documentation and the clean and concise reference.

But the project I'm working on relies on the popular `uuid` crate for user IDs (specifically `uuid::Uuid`). Though I haven't been able to find a way to either implement `yarte::Render` for `Uuid` since both are external items. My current mitigation involves a variant of my data that has `std::string::String` instead. This is possible due to the implementation of `alloc::string::ToString` for `uuid::Uuid`.

My request is then to either get support the `uuid` crate (as a feature) or ideally a blanket implementation of `Render` for all structs that implement `alloc::string::ToString`. A blanket implementation would not only solve my problem, but also possible resolve the problem for other crates that provide custom data types that support the widely used `alloc::string::ToString`.

I'm sorry if I wrote too much. Just noticed how long this has got.

**Comment by botika** [comment]
Yes, of course, it is very easy to implement, this afternoon or night, CET, I implement it. Thanks!

**Comment by Chaostheorie** [comment]
Thank you.

**Comment by botika** [comment]
I don't want to have to depend on uuid. Is it okay if I put a feature for the uuid render? Or another build with these implementations? How about?

**Comment by botika** [comment]
For `Render`trait just use safe expression 
```handlebars
{{{ uuid }}}
```
