### ISSUE TITLE
Possible partial parser bug

### ISSUE THREAD

**Issue by gxtaillon** [botika/yarte#229]
Hello,

I can work around this issue but it would be very convenient to be able to declare styles to put the `<head>` in the same hbs file where they are used. 

I'm getting a macro panick when the character '}' is present in a partial's attribute value[0]:

```rust
error: proc macro panicked
   --> src/bin/x.rs:y:z
    |
127 |         .body(auto!(ywrite_min!(String, "{{> pages/query }}"))))
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: message: called `Option::unwrap()` on a `None` value
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Eg:
```rust
{{#> root/base style = "form textarea { box-sizing: border-box; width: 100%; max-width:1024px; }" }}
-----------------------------------------------------------------------------------------------^
```

Also fails with
```rust
}}
}}}
\}
\\}
```

System versions:
```
yarte 0.15.4
rustc 1.53.0 (53cb7b09b 2021-06-17)
binary: rustc
commit-hash: 53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b
commit-date: 2021-06-17
host: x86_64-unknown-linux-gnu
release: 1.53.0
LLVM version: 12.0.1
```

Best,

[0] https://yarte.netlify.app/templating/partial.html

**Comment by botika** [comment]
You were using a incomplete partial block, just remove # . And yes Error
output sucks , I will improve it.

**Comment by botika** [comment]
@gxtaillon Did this solve the problem? Any questions? Close?

**Comment by gxtaillon** [comment]
Removing the # produces another error that looks like https://github.com/botika/yarte/issues/211.

Closing since I can work around it

Thank you

**Comment by botika** [comment]
You must have an error in the template. Use the derivative that does not have that bug in the error output, you can use it only to develop the templates. 
I'm sorry, as you can see, I already have the issue, but I have problems with Spanish justice, these incompetent fascists don't stop fucking with me. 

Soon I will be calmer and I will put full time. Thanks for use yarte

**Comment by botika** [comment]
Close in favor of #211
