### ISSUE TITLE
Warning: unused borrow must be used

### ISSUE THREAD

**Issue by nsabovic** [botika/yarte#233]
As of recently, each time I compile my CLI app that uses Yarte i get a bunch of these:

```
warning: unused borrow that must be used
 --> src/report/generate_html.rs:5:10
  |
5 | #[derive(Template)]
  |          ^^^^^^^^ the borrow produces a value
  |
  = note: this warning originates in the derive macro `Template` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Looking into it with `cargo expand` I see generated code like this:

```rust
&(self.surface_type).__renders_it(_fmt)?;
``` 

Which, as far as I understand, calls `__renders_it()`, and grabs the reference of the returned `Result` instead of grabbing the reference of `self.surface_type`, hence the warnings.

**Comment by Roms1383** [comment]
Hi everybody !
@botika just to mention but I also get the very same warning in current version `0.15.5`.

**Comment by botika** [comment]
@Roms1383 Can you explain the case to me?

**Comment by Roms1383** [comment]
Yes @botika, sure:

---

#### platform
<img width="423" alt="dev-machine" src="https://user-images.githubusercontent.com/21016014/141877083-99cfabb6-cd12-4758-9547-15c165d7dd0d.png">

---

#### context
- 📦 cargo 1.56.0 (4ed5d137b 2021-10-04)
- ⚙️ rustc 1.56.1 (59eed8a2a 2021-11-01)
- 📜 rustup 1.24.3 (ce5817a94 2021-05-31)
- 💄 rustfmt 1.4.37-stable (59eed8a2 2021-11-01)
- ✉️ yarte = "0.15.5"

---

#### sample of code

```rust
#[derive(Template)] // ⚠️ unused borrow that must be used the borrow produces a value
#[template(path = "email-verification")]
pub struct EmailVerification<'a> {
    url: &'a str,
    name: &'a str,
    is_applying: bool,
    code: &'a str,
    expiration: &'a str,
}
```

#### sample of template

📁 ./templates/email-verification.hbs
```hbs
{{#if code == "fr"}}
  {{> fr/email-verification }}
{{else}}
  {{> en/email-verification }}
{{/if}}
```
📁 ./templates/en/email-verification.hbs
```hbs
{{name}}

Welcome, we have acknowledged your registration.
Please verify your email address by clicking on the link below.

{{{url}}}

This verification link will expire on {{expiration}}
Once expired, please process with registration from the beginning again.

Thank you.
```

**Comment by botika** [comment]
@Roms1383 The changes are already in master. Can you confirm that they have solved the problem to get a new version?

**Comment by Roms1383** [comment]
@botika I tried quickly from `master` and indeed the warnings are gone ! 🎉

**Comment by botika** [comment]
Thank you very much for participating in the development of yarte, I release a new version throughout the morning (CET) (It's that I'm in a meeting now (don't tell my boss) :smiley_cat: )
