### ISSUE TITLE
Benchmarks to back up "fastest template engine" claim?

### ISSUE THREAD

**Issue by Phrohdoh** [botika/yarte#99]
Do you have benchmarks that back up the claim that `yarte` is the "fastest template engine?"

**Comment by botika** [comment]
You can see in:
- https://github.com/botika/yarte#is-it-really-the-fastest
- https://github.com/botika/template-bench-rs
- https://travis-ci.org/github/botika/template-bench-rs/jobs/676386705#L1024
- `cargo asm`

**Comment by Phrohdoh** [comment]
I completely missed the link to the benchmarks in the readme, my apologies!

Thanks for the quick response. :-)
